# Generated by Django 5.2.4 on 2026-06-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField()),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=50)),
                ('Course_title', models.CharField(max_length=50)),
                ('Credit', models.IntegerField(max_length=5)),
                ('Student', models.CharField(max_length=200)),
                ('Lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.lecturer')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.level')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timeslot', models.CharField(max_length=100)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
            ],
        ),
    ]
