# Generated by Django 5.2.4 on 2026-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Credit',
            field=models.IntegerField(),
        ),
    ]
