# Generated by Django 5.2.4 on 2026-06-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_course_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
