# Generated by Django 5.2.4 on 2026-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_lecturer_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Type',
            field=models.CharField(default='Lecture Hall', max_length=200),
        ),
    ]
