# Generated by Django 5.2.4 on 2026-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
