# Generated by Django 5.2.4 on 2026-06-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_room_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=200)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Duration', models.DurationField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot'),
        ),
    ]
