# Generated by Django 5.2.4 on 2026-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_timeslot_alter_schedule_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
